export type PublicEnvVariableName = keyof typeof publicEnvVariableName

export const publicEnvVariableName = {
  PUBLIC_ENV_MODE: "PUBLIC_ENV_MODE",

  PUBLIC_BASE_URL_SITE: "PUBLIC_BASE_URL_SITE",
  PUBLIC_BASE_URL_APP: "PUBLIC_BASE_URL_APP",
  PUBLIC_BASE_URL_API: "PUBLIC_BASE_URL_API",
  PUBLIC_BASE_URL_CONVEX: "PUBLIC_BASE_URL_CONVEX",

  PUBLIC_MAILTO_CONTACT_URL: "PUBLIC_MAILTO_CONTACT_URL",

  PUBLIC_GITHUB_CLIENT_ID: "GITHUB_CLIENT_ID",
  PUBLIC_GOOGLE_CLIENT_ID: "PUBLIC_GOOGLE_CLIENT_ID",
  PUBLIC_SIGNED_IN_DEFAULT_PATH: "PUBLIC_SIGNED_IN_DEFAULT_PATH",

  PUBLIC_EMAIL_TEMPLATE_HOMEPAGE_URL: "PUBLIC_EMAIL_TEMPLATE_HOMEPAGE_URL",
  PUBLIC_EMAIL_TEMPLATE_HOMEPAGE_NAME: "PUBLIC_EMAIL_TEMPLATE_HOMEPAGE_NAME",
  PUBLIC_EMAIL_TEMPLATE_HOMEPAGE_MOTTO: "PUBLIC_EMAIL_TEMPLATE_HOMEPAGE_MOTTO",

  PUBLIC_POSTHOG_APP_ID: "PUBLIC_POSTHOG_APP_ID",
  PUBLIC_POSTHOG_APP_API: "PUBLIC_POSTHOG_APP_API",
  PUBLIC_POSTHOG_APP_UI: "PUBLIC_POSTHOG_APP_UI",
} as const
