export type PrivateAppEnvVariableName = keyof typeof privateAppEnvVariableName

export const privateAppEnvVariableName = {
  // mailjet
  AUTH_MAILJET_APIKEY_PUBLIC: "AUTH_MAILJET_APIKEY_PUBLIC",
  AUTH_MAILJET_APIKEY_PRIVATE: "AUTH_MAILJET_APIKEY_PRIVATE",
  AUTH_MAILJET_SENDER_ADDRESS: "AUTH_MAILJET_SENDER_ADDRESS",
  AUTH_MAILJET_SENDER_NAME: "AUTH_MAILJET_SENDER_NAME",
  // resend
  AUTH_RESEND_API_KEY: "AUTH_RESEND_API_KEY",
  AUTH_RESEND_SENDER_ADDRESS: "AUTH_RESEND_SENDER_ADDRESS",
  AUTH_RESEND_SENDER_NAME: "AUTH_RESEND_SENDER_NAME",
} as const
