const mountedPageDemoRoutes = new Set([
  "/",
  "/overview",
  "/todo",
  "/sign-in",
  "/sign-in-enter-otp",
  "/sign-in-error",
  "/sign-up",
  "/sign-up-confirm-email",
  "/sso",
  "/profile",
  "/profile/edit",
  "/profile/change-password",
  "/profile/change-email",
  "/profile/update-image",
  "/profile/delete",
  "/u/:username",
  "/profile/api-keys",
  "/org",
  "/org/create",
  "/org/:orgHandle",
  "/org/:orgHandle/edit",
  "/org/:orgHandle/leave",
  "/org/:orgHandle/remove",
  "/org/:orgHandle/members",
  "/org/:orgHandle/members/add",
  "/org/:orgHandle/members/:memberId/view",
  "/org/:orgHandle/members/:memberId/edit",
  "/org/:orgHandle/members/:memberId/remove",
  "/org/:orgHandle/invitations",
  "/org/:orgHandle/invitations/add",
  "/org/:orgHandle/invitations/:invitationCode/accept",
  "/w/list",
  "/w/add",
  "/w/:workspaceHandle/view",
  "/w/:workspaceHandle/edit",
  "/w/:workspaceHandle/remove",
  "/workspace/:workspaceHandle/members",
  "/workspace/:workspaceHandle/members/add",
  "/workspace/:workspaceHandle/members/:memberId/edit",
  "/workspace/:workspaceHandle/members/:memberId/delete",
  "/workspace/:workspaceHandle/invitations",
  "/workspace/:workspaceHandle/invitations/add",
  "/invite/:invitationCode/accept",
  "/resources",
  "/resources/add",
  "/resources/:resourceId",
  "/resources/:resourceId/edit",
  "/resources/:resourceId/remove",
])

/** Indicates that PageDemoBoundary has an isolated renderer for this registered route. */
export function pageDemoRouteIsMounted(route: string) {
  return mountedPageDemoRoutes.has(route)
}
