// Demo identifiers mirror generateDemoList: Demo*.tsx under src/pages becomes pages/Demo*.
// Keep this separate from demoList.ts, which remains generator-owned for component examples.
const entries = [
  { route: "/sign-up", title: "Sign up", pageImport: "#src/auth/ui/sign_up/SignUpPage.tsx", params: {} },
  {
    route: "/sign-up-confirm-email",
    title: "Confirm email",
    pageImport: "#src/auth/ui/sign_up/email/SignUpConfirmEmailPage.tsx",
    params: {},
  },
  { route: "/sign-in", title: "Sign in", pageImport: "#src/auth/ui/sign_in/page/SignInPage.tsx", params: {} },
  {
    route: "/sign-in-enter-otp",
    title: "Enter sign-in code",
    pageImport: "#src/auth/ui/sign_in/via_email_enter_otp/SignInViaEmailEnterOtpPage.tsx",
    params: {},
  },
  {
    route: "/sign-in-error",
    title: "Sign-in error",
    pageImport: "#src/auth/ui/sign_in/error/SignInErrorPage.tsx",
    params: {},
  },
  { route: "/sso", title: "Single sign-on", pageImport: "#src/sso/ui/AllgroupsSsoPage.tsx", params: {} },
  { route: "/profile", title: "My profile", pageImport: "#src/auth/ui/profile_me/UserProfileMePage.tsx", params: {} },
  {
    route: "/profile/api-keys",
    title: "My API keys",
    pageImport: "#src/auth/ui/profile_me/UserProfileMeApiKeysPage.tsx",
    params: {},
  },
  {
    route: "/profile/edit",
    title: "Edit profile",
    pageImport: "#src/auth/ui/profile_me/UserProfileMeEditPage.tsx",
    params: {},
  },
  {
    route: "/profile/change-password",
    title: "Change password",
    pageImport: "#src/auth/ui/profile_me/UserProfileMeChangePasswordPage.tsx",
    params: {},
  },
  {
    route: "/profile/change-email",
    title: "Change email",
    pageImport: "#src/auth/ui/profile_me/UserProfileMeChangeEmailPage.tsx",
    params: {},
  },
  {
    route: "/profile/update-image",
    title: "Update profile image",
    pageImport: "#src/auth/ui/profile_me/UserProfileMeImagePage.tsx",
    params: {},
  },
  {
    route: "/profile/delete",
    title: "Delete account",
    pageImport: "#src/auth/ui/profile_me/UserProfileMeDeletePage.tsx",
    params: {},
  },
  {
    route: "/u/:username",
    title: "User profile",
    pageImport: "#src/auth/ui/profile/UserProfilePage.tsx",
    params: { username: "sample-user" },
  },
  { route: "/", title: "Overview", pageImport: "#src/app/pages/OverviewPage.tsx", params: {} },
  { route: "/overview", title: "Overview", pageImport: "#src/app/pages/OverviewPage.tsx", params: {} },
  { route: "/todo", title: "To do", pageImport: "#src/ui/pages/TodoPage.tsx", params: {} },
  { route: "/org", title: "Organizations", pageImport: "#src/org/org_ui/list/OrgListPage.tsx", params: {} },
  {
    route: "/org/create",
    title: "Create organization",
    pageImport: "#src/org/org_ui/mutate/OrgAddPage.tsx",
    params: {},
  },
  {
    route: "/org/:orgHandle",
    title: "Organization",
    pageImport: "#src/org/org_ui/view/OrgViewPage.tsx",
    params: { orgHandle: "sample-org" },
  },
  {
    route: "/org/:orgHandle/edit",
    title: "Edit organization",
    pageImport: "#src/org/org_ui/mutate/OrgEditPage.tsx",
    params: { orgHandle: "sample-org" },
  },
  {
    route: "/org/:orgHandle/leave",
    title: "Leave organization",
    pageImport: "#src/org/org_ui/mutate/OrgLeavePage.tsx",
    params: { orgHandle: "sample-org" },
  },
  {
    route: "/org/:orgHandle/remove",
    title: "Remove organization",
    pageImport: "#src/org/org_ui/mutate/OrgDeletePage.tsx",
    params: { orgHandle: "sample-org" },
  },
  {
    route: "/org/:orgHandle/members",
    title: "Organization members",
    pageImport: "#src/org/member_ui/list/OrgMemberListPage.tsx",
    params: { orgHandle: "sample-org" },
  },
  {
    route: "/org/:orgHandle/members/add",
    title: "Add organization member",
    pageImport: "#src/org/member_ui/mutate/OrgMemberAddPage.tsx",
    params: { orgHandle: "sample-org" },
  },
  {
    route: "/org/:orgHandle/members/:memberId/view",
    title: "Organization member",
    pageImport: "#src/ui/pages/TodoPage.tsx",
    params: { orgHandle: "sample-org", memberId: "member-1" },
  },
  {
    route: "/org/:orgHandle/members/:memberId/edit",
    title: "Edit organization member",
    pageImport: "#src/org/member_ui/mutate/OrgMemberEditPage.tsx",
    params: { orgHandle: "sample-org", memberId: "member-1" },
  },
  {
    route: "/org/:orgHandle/members/:memberId/remove",
    title: "Remove organization member",
    pageImport: "#src/org/member_ui/mutate/OrgMemberDeletePage.tsx",
    params: { orgHandle: "sample-org", memberId: "member-1" },
  },
  {
    route: "/org/:orgHandle/invitations",
    title: "Organization invitations",
    pageImport: "#src/org/invitation_ui/list/OrgInvitationListPage.tsx",
    params: { orgHandle: "sample-org" },
  },
  {
    route: "/org/:orgHandle/invitations/add",
    title: "Invite to organization",
    pageImport: "#src/org/invitation_ui/mutate/OrgInvitationAddPage.tsx",
    params: { orgHandle: "sample-org" },
  },
  {
    route: "/org/:orgHandle/invitations/:invitationCode/accept",
    title: "Accept organization invitation",
    pageImport: "#src/org/invitation_ui/accept/OrgInvitationAcceptPage.tsx",
    params: { orgHandle: "sample-org", invitationCode: "invite-1" },
  },
  {
    route: "/w/list",
    title: "Workspaces",
    pageImport: "#src/workspace/workspace_ui/list/WorkspaceListPage.tsx",
    params: {},
  },
  {
    route: "/w/add",
    title: "Create workspace",
    pageImport: "#src/workspace/workspace_ui/mutate/WorkspaceAddPage.tsx",
    params: {},
  },
  {
    route: "/w/:workspaceHandle/view",
    title: "Workspace",
    pageImport: "#src/workspace/workspace_ui/view/WorkspaceViewPage.tsx",
    params: { workspaceHandle: "sample-workspace" },
  },
  {
    route: "/w/:workspaceHandle/edit",
    title: "Edit workspace",
    pageImport: "#src/workspace/workspace_ui/mutate/WorkspaceEditPage.tsx",
    params: { workspaceHandle: "sample-workspace" },
  },
  {
    route: "/w/:workspaceHandle/remove",
    title: "Remove workspace",
    pageImport: "#src/workspace/workspace_ui/mutate/WorkspaceDeletePage.tsx",
    params: { workspaceHandle: "sample-workspace" },
  },
  {
    route: "/workspace/:workspaceHandle/members",
    title: "Workspace members",
    pageImport: "#src/workspace/member_ui/list/WorkspaceMemberListPage.tsx",
    params: { workspaceHandle: "sample-workspace" },
  },
  {
    route: "/workspace/:workspaceHandle/members/add",
    title: "Add workspace member",
    pageImport: "#src/workspace/member_ui/mutate/WorkspaceMemberAddPage.tsx",
    params: { workspaceHandle: "sample-workspace" },
  },
  {
    route: "/workspace/:workspaceHandle/members/:memberId/edit",
    title: "Edit workspace member",
    pageImport: "#src/workspace/member_ui/mutate/WorkspaceMemberEditPage.tsx",
    params: { workspaceHandle: "sample-workspace", memberId: "member-1" },
  },
  {
    route: "/workspace/:workspaceHandle/members/:memberId/delete",
    title: "Remove workspace member",
    pageImport: "#src/workspace/member_ui/mutate/WorkspaceMemberDeletePage.tsx",
    params: { workspaceHandle: "sample-workspace", memberId: "member-1" },
  },
  {
    route: "/workspace/:workspaceHandle/invitations",
    title: "Workspace invitations",
    pageImport: "#src/workspace/invitation_ui/list/WorkspaceInvitationListPage.tsx",
    params: { workspaceHandle: "sample-workspace" },
  },
  {
    route: "/workspace/:workspaceHandle/invitations/add",
    title: "Invite to workspace",
    pageImport: "#src/workspace/invitation_ui/mutate/WorkspaceInvitationAddPage.tsx",
    params: { workspaceHandle: "sample-workspace" },
  },
  {
    route: "/invite/:invitationCode/accept",
    title: "Accept workspace invitation",
    pageImport: "#src/workspace/invitation_ui/accept/WorkspaceInvitationAcceptPage.tsx",
    params: { invitationCode: "invite-1" },
  },
  { route: "/resources", title: "Resources", pageImport: "#src/resource/ui/list/ResourceListPage.tsx", params: {} },
  {
    route: "/resources/add",
    title: "Add resource",
    pageImport: "#src/resource/ui/mutate/ResourceAddPage.tsx",
    params: {},
  },
  {
    route: "/resources/:resourceId",
    title: "Resource",
    pageImport: "#src/resource/ui/view/ResourceViewPage.tsx",
    params: { resourceId: "sample-resource-1" },
  },
  {
    route: "/resources/:resourceId/edit",
    title: "Edit resource",
    pageImport: "#src/resource/ui/mutate/ResourceEditPage.tsx",
    params: { resourceId: "sample-resource-1" },
  },
  {
    route: "/resources/:resourceId/remove",
    title: "Remove resource",
    pageImport: "#src/resource/ui/mutate/ResourceDeletePage.tsx",
    params: { resourceId: "sample-resource-1" },
  },
] as const

export const pageRouteInventory = entries.map((entry) => ({
  ...entry,
  demoEntry: `pages/Demo${entry.route === "/" ? "Root" : entry.route.replace(/^\//, "").replaceAll(/[^a-zA-Z0-9]/g, "")}`,
}))
