export type PrivateEnvVariableName = keyof typeof privateEnvVariableName

export const privateEnvVariableName = {
  // base urls
  BASE_URL_EMAIL_GENERATOR: "BASE_URL_EMAIL_GENERATOR",
  // auth
  AUTH_SECRET: "AUTH_SECRET",
  GITHUB_CLIENT_SECRET: "GITHUB_CLIENT_SECRET",
  GOOGLE_CLIENT_SECRET: "GOOGLE_CLIENT_SECRET",
  MICROSOFT_CLIENT_SECRET: "MICROSOFT_CLIENT_SECRET",
  // storage / r2
  R2_ACCOUNT_ID: "R2_ACCOUNT_ID",
  R2_ACCESS_KEY_ID: "R2_ACCESS_KEY_ID",
  R2_SECRET_ACCESS_KEY: "R2_SECRET_ACCESS_KEY",
  R2_BUCKET_NAME: "R2_BUCKET_NAME",
  // messaging / telegram
  TELEGRAM_TOKEN: "TELEGRAM_TOKEN",
  TELEGRAM_CHAT_ID_AUTH: "TELEGRAM_CHAT_ID_AUTH",
  TELEGRAM_CHAT_ID_ERRORS: "TELEGRAM_CHAT_ID_ERRORS",
  TELEGRAM_CHAT_ID_SUPPORT: "TELEGRAM_CHAT_ID_SUPPORT",
  // messaging / email / mailjet
  AUTH_MAILJET_APIKEY_PUBLIC: "AUTH_MAILJET_APIKEY_PUBLIC",
  AUTH_MAILJET_APIKEY_PRIVATE: "AUTH_MAILJET_APIKEY_PRIVATE",
  AUTH_MAILJET_SENDER_ADDRESS: "AUTH_MAILJET_SENDER_ADDRESS",
  AUTH_MAILJET_SENDER_NAME: "AUTH_MAILJET_SENDER_NAME",
  // messaging / email / resend
  AUTH_RESEND_API_KEY: "AUTH_RESEND_API_KEY",
  AUTH_RESEND_SENDER_ADDRESS: "AUTH_RESEND_SENDER_ADDRESS",
  AUTH_RESEND_SENDER_NAME: "AUTH_RESEND_SENDER_NAME",
} as const
