export type PublicEnvVariableName = keyof typeof publicEnvVariableName

export const publicEnvVariableName = {
  PUBLIC_ENV_MODE: "PUBLIC_ENV_MODE",

  PUBLIC_BASE_URL_SITE: "PUBLIC_BASE_URL_SITE",
  PUBLIC_BASE_URL_APP: "PUBLIC_BASE_URL_APP",
  PUBLIC_BASE_URL_API: "PUBLIC_BASE_URL_API",
  PUBLIC_BASE_URL_CONVEX: "PUBLIC_BASE_URL_CONVEX",

  PUBLIC_GITHUB_CLIENT_ID: "PUBLIC_GITHUB_CLIENT_ID",
  PUBLIC_GOOGLE_CLIENT_ID: "PUBLIC_GOOGLE_CLIENT_ID",
  PUBLIC_MICROSOFT_CLIENT_ID: "PUBLIC_MICROSOFT_CLIENT_ID",

  PUBLIC_POSTHOG_APP_ID: "PUBLIC_POSTHOG_APP_ID",
} as const
